import argparse
import html
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Optional

import pandas as pd
import requests
from dotenv import load_dotenv


def load_env() -> None:
    env_path = Path(__file__).resolve().parents[1] / ".env"
    if env_path.exists():
        load_dotenv(env_path)


def normalize_name(value: str) -> str:
    return html.unescape(str(value or "").strip()).lower()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Update WordPress restaurant posts with geocode data from Excel."
    )
    parser.add_argument(
        "--file",
        required=True,
        help="Path to the Excel file generated by geocode_restaurant_locations.py",
    )
    parser.add_argument(
        "--base-url",
        default=os.getenv("WP_BASE_URL", "https://byobmap.com"),
        help="WordPress site base URL (default: https://byobmap.com)",
    )
    parser.add_argument(
        "--username",
        default=os.getenv("WP_USERNAME"),
        help="WordPress username (can also be provided via WP_USERNAME env variable).",
    )
    parser.add_argument(
        "--password",
        default=os.getenv("WP_APP_PASSWORD"),
        help="Application password (or WP_APP_PASSWORD env variable).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="If set, only report matches without sending update requests.",
    )
    return parser.parse_args()


def ensure_credentials(args: argparse.Namespace) -> None:
    missing: Dict[str, Optional[str]] = {
        "username": args.username,
        "password": args.password,
    }
    missing = {k: v for k, v in missing.items() if not v}
    if missing:
        keys = ", ".join(missing.keys())
        raise RuntimeError(
            f"Missing WordPress credentials ({keys}). "
            "Provide via CLI arguments or environment variables."
        )


def search_restaurant(
    session: requests.Session, base_url: str, name: str
) -> list[dict]:
    response = session.get(
        f"{base_url.rstrip('/')}/wp-json/wp/v2/restaurant",
        params={"search": name, "per_page": 100},
        timeout=20,
    )
    response.raise_for_status()
    return response.json()


def find_exact_match(results: list[dict], target: str) -> Optional[dict]:
    normalized_target = normalize_name(target)
    matches = [
        item
        for item in results
        if normalize_name(item.get("title", {}).get("rendered")) == normalized_target
    ]
    if len(matches) == 1:
        return matches[0]
    return None


def build_meta_payload(row: pd.Series) -> dict:
    meta = {}
    if pd.notna(row.get("Latitude")):
        meta["latitude"] = str(row["Latitude"])
    if pd.notna(row.get("Longitude")):
        meta["longitude"] = str(row["Longitude"])
    if pd.notna(row.get("Geocode_Status")):
        meta["geocode_status"] = str(row["Geocode_Status"])
    if pd.notna(row.get("Matched_Address")):
        meta["matched_address"] = str(row["Matched_Address"])
    meta["geocode_updated_at"] = datetime.now(timezone.utc).isoformat()
    return meta


def update_post(
    session: requests.Session, base_url: str, post_id: int, meta: dict, dry_run: bool
) -> requests.Response:
    if dry_run:
        class _DummyResponse:
            status_code = 200

            def json(self):
                return {}

        return _DummyResponse()  # type: ignore[return-value]

    response = session.post(
        f"{base_url.rstrip('/')}/wp-json/wp/v2/restaurant/{post_id}",
        json={"meta": meta},
        timeout=20,
    )
    response.raise_for_status()
    return response


def main() -> None:
    load_env()
    args = parse_args()
    ensure_credentials(args)

    excel_path = Path(args.file)
    if not excel_path.exists():
        raise FileNotFoundError(f"Excel file not found: {excel_path}")

    df = pd.read_excel(excel_path)
    required_columns = {"Name", "Latitude", "Longitude"}
    missing_cols = required_columns - set(df.columns)
    if missing_cols:
        raise RuntimeError(f"Missing required columns in Excel: {', '.join(missing_cols)}")

    session = requests.Session()
    session.auth = (args.username, args.password)

    success_rows = []
    failures = []

    for _, row in df.iterrows():
        name = row.get("Name")
        lat = row.get("Latitude")
        lng = row.get("Longitude")

        if not name or pd.isna(lat) or pd.isna(lng):
            failures.append(
                {
                    "Name": name,
                    "Reason": "Missing name/latitude/longitude",
                }
            )
            continue

        try:
            results = search_restaurant(session, args.base_url, name)
        except requests.HTTPError as exc:
            failures.append({"Name": name, "Reason": f"HTTP error during search: {exc}"})
            continue
        except requests.RequestException as exc:
            failures.append({"Name": name, "Reason": f"Network error during search: {exc}"})
            continue

        match = find_exact_match(results, name)
        if not match:
            failures.append(
                {
                    "Name": name,
                    "Reason": f"No unique exact match found (found {len(results)} results)",
                }
            )
            continue

        post_id = match["id"]
        meta = build_meta_payload(row)

        try:
            update_post(session, args.base_url, post_id, meta, args.dry_run)
            success_rows.append({"Name": name, "Post_ID": post_id})
        except requests.HTTPError as exc:
            failures.append({"Name": name, "Reason": f"HTTP error during update: {exc}"})
        except requests.RequestException as exc:
            failures.append({"Name": name, "Reason": f"Network error during update: {exc}"})

    print("\n=== Summary ===")
    print(f"Total rows: {len(df)}")
    print(f"Success: {len(success_rows)}")
    print(f"Failures: {len(failures)}")

    if failures:
        failure_path = excel_path.with_name(f"{excel_path.stem}_update_failures.xlsx")
        pd.DataFrame(failures).to_excel(failure_path, index=False)
        print(f"Failure report saved to: {failure_path}")


if __name__ == "__main__":
    main()


