// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class RestaurantCardComponentHandle extends ffai.ProjectComponentHandle<RestaurantCardParams, RestaurantCardState> {
  RestaurantCardComponentHandle()
    : super(
        name: "RestaurantCard",
        key: "Container_8pwtg3ek",
        params: const RestaurantCardParams(),
        state: const RestaurantCardState(),
        widgets: RestaurantCardWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "corkageFeeType": ffai.string,
          "cuisineType": ffai.string,
          "cuisineTypeNote": ffai.string,
          "imageUrl": ffai.string,
          "restaurantName": ffai.string,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? corkageFeeType = ffai.kUnsetComponentArg,
    Object? cuisineType = ffai.kUnsetComponentArg,
    Object? cuisineTypeNote = ffai.kUnsetComponentArg,
    Object? imageUrl = ffai.kUnsetComponentArg,
    Object? restaurantName = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(corkageFeeType)) "corkageFeeType": corkageFeeType,
        if (!ffai.isUnsetComponentArg(cuisineType)) "cuisineType": cuisineType,
        if (!ffai.isUnsetComponentArg(cuisineTypeNote)) "cuisineTypeNote": cuisineTypeNote,
        if (!ffai.isUnsetComponentArg(imageUrl)) "imageUrl": imageUrl,
        if (!ffai.isUnsetComponentArg(restaurantName)) "restaurantName": restaurantName,
      },
    );
  }
}

final class RestaurantCardParams {
  const RestaurantCardParams();
  ffai.ProjectParamHandle get corkageFeeType =>
      const ffai.ProjectParamHandle(
        name: "corkageFeeType",
        key: "9s864biy",
        typeName: "String",
      );
  ffai.ProjectParamHandle get cuisineType =>
      const ffai.ProjectParamHandle(
        name: "cuisineType",
        key: "mw3w83yp",
        typeName: "String",
      );
  ffai.ProjectParamHandle get cuisineTypeNote =>
      const ffai.ProjectParamHandle(
        name: "cuisineTypeNote",
        key: "mntaxu08",
        typeName: "String",
      );
  ffai.ProjectParamHandle get imageUrl =>
      const ffai.ProjectParamHandle(
        name: "imageUrl",
        key: "1mxitmf2",
        typeName: "String",
      );
  ffai.ProjectParamHandle get restaurantName =>
      const ffai.ProjectParamHandle(
        name: "restaurantName",
        key: "tjl5wjlo",
        typeName: "String",
      );
}

final class RestaurantCardState {
  const RestaurantCardState();
}

abstract final class RestaurantCardWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_8pwtg3ek",
      type: "Container",
      path: "RestaurantCard",
      name: "RestaurantCard",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Container_0s6ihdg5",
          type: "Container",
          path: "RestaurantCard.children[0]",
          name: "Container Margin",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Container_7hjqc9u1",
              type: "Container",
              path: "RestaurantCard.children[0].children[0]",
              name: "Container",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Row_o0mc0vew",
                  type: "Row",
                  path: "RestaurantCard.children[0].children[0].children[0]",
                  name: "CardRow",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Container_al2l7y54",
                      type: "Container",
                      path: "RestaurantCard.children[0].children[0].children[0].children[0]",
                      name: "ImageSection",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Image_xuo1vwbh",
                          type: "Image",
                          path: "RestaurantCard.children[0].children[0].children[0].children[0].children[0]",
                          name: "CoverImage",
                        ),
                      ],
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "Container_ussbbyxd",
                      type: "Container",
                      path: "RestaurantCard.children[0].children[0].children[0].children[1]",
                      name: "InfoSection",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Column_g7hc8ht7",
                          type: "Column",
                          path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0]",
                          name: "InfoColumn",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Text_395l7d4l",
                              type: "Text",
                              path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[0]",
                              name: "NameText",
                            ),
                            ffai.ProjectWidgetHandle(
                              key: "Container_xr0m7fyi",
                              type: "Container",
                              path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[1]",
                              name: "CuisineTagsContainer",
                              children: <ffai.ProjectWidgetHandle>[
                                ffai.ProjectWidgetHandle(
                                  key: "ListView_qyw7c2l4",
                                  type: "ListView",
                                  path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[1].children[0]",
                                  name: "CuisineTagsList",
                                  children: <ffai.ProjectWidgetHandle>[
                                    ffai.ProjectWidgetHandle(
                                      key: "Container_onfuqtbh",
                                      type: "Container",
                                      path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[1].children[0].children[0]",
                                      name: "CuisineTag",
                                      triggers: const <String>[
                                        "ON_TAP",
                                      ],
                                      children: <ffai.ProjectWidgetHandle>[
                                        ffai.ProjectWidgetHandle(
                                          key: "Text_9pcdcqqn",
                                          type: "Text",
                                          path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[1].children[0].children[0].children[0]",
                                          name: "CuisineTagText",
                                        ),
                                      ],
                                    ),
                                  ],
                                ),
                              ],
                            ),
                            ffai.ProjectWidgetHandle(
                              key: "Row_km3xrvty",
                              type: "Row",
                              path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[2]",
                              name: "BadgeRow",
                              children: <ffai.ProjectWidgetHandle>[
                                ffai.ProjectWidgetHandle(
                                  key: "Container_yq6dznxw",
                                  type: "Container",
                                  path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[2].children[0]",
                                  name: "FreeBadge",
                                  children: <ffai.ProjectWidgetHandle>[
                                    ffai.ProjectWidgetHandle(
                                      key: "Text_fp4kmkkq",
                                      type: "Text",
                                      path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[2].children[0].children[0]",
                                      name: "FreeBadgeText",
                                      text: "Free BYOB",
                                    ),
                                  ],
                                ),
                                ffai.ProjectWidgetHandle(
                                  key: "Container_kfhipqkn",
                                  type: "Container",
                                  path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[2].children[1]",
                                  name: "CorkageFeeBadge",
                                  children: <ffai.ProjectWidgetHandle>[
                                    ffai.ProjectWidgetHandle(
                                      key: "Text_kb2zejw1",
                                      type: "Text",
                                      path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[2].children[1].children[0]",
                                      name: "CorkageAmountText",
                                      text: "Corkage Fee",
                                    ),
                                  ],
                                ),
                                ffai.ProjectWidgetHandle(
                                  key: "Container_7vo4maum",
                                  type: "Container",
                                  path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[2].children[2]",
                                  name: "AskUsBadge",
                                  children: <ffai.ProjectWidgetHandle>[
                                    ffai.ProjectWidgetHandle(
                                      key: "Text_bwqc0st4",
                                      type: "Text",
                                      path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[2].children[2].children[0]",
                                      name: "AskUsText",
                                      text: "Ask Us",
                                    ),
                                  ],
                                ),
                              ],
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

