// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class RestaurantCardComponentHandle extends ffai.ProjectComponentHandle<RestaurantCardParams, RestaurantCardState> {
  RestaurantCardComponentHandle()
    : super(
        name: "RestaurantCard",
        key: "Container_8pwtg3ek",
        params: const RestaurantCardParams(),
        state: const RestaurantCardState(),
        widgets: RestaurantCardWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "corkageFeeType": ffai.string,
          "cuisineType": ffai.string,
          "imageUrl": ffai.string,
          "restaurantName": ffai.string,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? corkageFeeType = ffai.kUnsetComponentArg,
    Object? cuisineType = ffai.kUnsetComponentArg,
    Object? imageUrl = ffai.kUnsetComponentArg,
    Object? restaurantName = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(corkageFeeType)) "corkageFeeType": corkageFeeType,
        if (!ffai.isUnsetComponentArg(cuisineType)) "cuisineType": cuisineType,
        if (!ffai.isUnsetComponentArg(imageUrl)) "imageUrl": imageUrl,
        if (!ffai.isUnsetComponentArg(restaurantName)) "restaurantName": restaurantName,
      },
    );
  }
}

final class RestaurantCardParams {
  const RestaurantCardParams();
  ffai.ProjectParamHandle get corkageFeeType =>
      const ffai.ProjectParamHandle(
        name: "corkageFeeType",
        key: "9s864biy",
        typeName: "String",
      );
  ffai.ProjectParamHandle get cuisineType =>
      const ffai.ProjectParamHandle(
        name: "cuisineType",
        key: "mw3w83yp",
        typeName: "String",
      );
  ffai.ProjectParamHandle get imageUrl =>
      const ffai.ProjectParamHandle(
        name: "imageUrl",
        key: "1mxitmf2",
        typeName: "String",
      );
  ffai.ProjectParamHandle get restaurantName =>
      const ffai.ProjectParamHandle(
        name: "restaurantName",
        key: "tjl5wjlo",
        typeName: "String",
      );
}

final class RestaurantCardState {
  const RestaurantCardState();
}

abstract final class RestaurantCardWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_8pwtg3ek",
      type: "Container",
      path: "RestaurantCard",
      name: "RestaurantCard",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Container_0s6ihdg5",
          type: "Container",
          path: "RestaurantCard.children[0]",
          name: "Container Margin",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Container_7hjqc9u1",
              type: "Container",
              path: "RestaurantCard.children[0].children[0]",
              name: "Container",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Row_ri8k490f",
                  type: "Row",
                  path: "RestaurantCard.children[0].children[0].children[0]",
                  name: "CardRow",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Container_gg372j8z",
                      type: "Container",
                      path: "RestaurantCard.children[0].children[0].children[0].children[0]",
                      name: "ImageSection",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Image_eke8hcp0",
                          type: "Image",
                          path: "RestaurantCard.children[0].children[0].children[0].children[0].children[0]",
                          name: "CoverImage",
                        ),
                      ],
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "Container_y6zbr3u1",
                      type: "Container",
                      path: "RestaurantCard.children[0].children[0].children[0].children[1]",
                      name: "InfoSection",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Column_4ezxws2w",
                          type: "Column",
                          path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0]",
                          name: "InfoColumn",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Text_is517qjt",
                              type: "Text",
                              path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[0]",
                              name: "NameText",
                            ),
                            ffai.ProjectWidgetHandle(
                              key: "Text_ph2a0va5",
                              type: "Text",
                              path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[1]",
                              name: "CuisineText",
                            ),
                            ffai.ProjectWidgetHandle(
                              key: "Row_kcjbp7ei",
                              type: "Row",
                              path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[2]",
                              name: "BadgeRow",
                              children: <ffai.ProjectWidgetHandle>[
                                ffai.ProjectWidgetHandle(
                                  key: "Container_9jdu3svq",
                                  type: "Container",
                                  path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[2].children[0]",
                                  name: "FreeBadge",
                                  children: <ffai.ProjectWidgetHandle>[
                                    ffai.ProjectWidgetHandle(
                                      key: "Text_hwv4c26e",
                                      type: "Text",
                                      path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[2].children[0].children[0]",
                                      name: "FreeBadgeText",
                                      text: "Free BYOB",
                                    ),
                                  ],
                                ),
                                ffai.ProjectWidgetHandle(
                                  key: "Container_gozr7lfh",
                                  type: "Container",
                                  path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[2].children[1]",
                                  name: "CorkageFeeBadge",
                                  children: <ffai.ProjectWidgetHandle>[
                                    ffai.ProjectWidgetHandle(
                                      key: "Text_enavtth8",
                                      type: "Text",
                                      path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[2].children[1].children[0]",
                                      name: "CorkageAmountText",
                                      text: "Corkage Fee",
                                    ),
                                  ],
                                ),
                                ffai.ProjectWidgetHandle(
                                  key: "Container_lcqycsav",
                                  type: "Container",
                                  path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[2].children[2]",
                                  name: "AskUsBadge",
                                  children: <ffai.ProjectWidgetHandle>[
                                    ffai.ProjectWidgetHandle(
                                      key: "Text_yy3exgcg",
                                      type: "Text",
                                      path: "RestaurantCard.children[0].children[0].children[0].children[1].children[0].children[2].children[2].children[0]",
                                      name: "AskUsText",
                                      text: "Ask Us",
                                    ),
                                  ],
                                ),
                              ],
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

