// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;
import 'components/restaurant_card.dart' show RestaurantCardComponentHandle;

abstract final class Components {
  static final restaurantCard = RestaurantCardComponentHandle();
  static final all = <ffai.ProjectComponentHandle>[
    restaurantCard,
  ];
}
