// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

abstract final class Project {
  static const id = "b-y-o-b-philly-a08xby";
  static const name = "BYOB Philly";
  static const sdkMetaVersion = 2;
}
