// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'dart:collection';

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

abstract final class Enums {
  static const all = <ffai.EnumHandle>[];
}

abstract final class Structs {
  static const all = <ffai.StructHandle>[];
}

abstract final class Collections {
  static const all = <ffai.ProjectCollectionHandle>[];
}

abstract final class Tables {
  static const all = <ffai.ProjectTableHandle>[];
}

abstract final class CustomCode {
  static const functions = <String>[
  ];
  static const actions = <String>[
  ];
  static const widgets = <String>[
  ];
}

