// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final homePageHandle = ffai.ProjectPageHandle<HomePageParams, HomePageState>(
  name: "HomePage",
  key: "Scaffold_oa99nxk6",
  route: "",
  params: const HomePageParams(),
  state: const HomePageState(),
  widgets: HomePageWidgets.tree,
);

final class HomePageParams {
  const HomePageParams();
}

final class HomePageState {
  const HomePageState();
  ffai.ProjectStateFieldHandle get filteredRestaurants =>
      const ffai.ProjectStateFieldHandle(
        name: "filteredRestaurants",
        key: "3g7kiw9o",
        typeName: "List<Document<restaurants>>",
      );
  ffai.ProjectStateFieldHandle get hasLocationPermission =>
      const ffai.ProjectStateFieldHandle(
        name: "hasLocationPermission",
        key: "ik28h6vw",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get isMapView =>
      const ffai.ProjectStateFieldHandle(
        name: "isMapView",
        key: "ydaix0z3",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get nearestThree =>
      const ffai.ProjectStateFieldHandle(
        name: "nearestThree",
        key: "0dj4dvb6",
        typeName: "List<Document<restaurants>>",
      );
  ffai.ProjectStateFieldHandle get restaurants =>
      const ffai.ProjectStateFieldHandle(
        name: "restaurants",
        key: "j1pgjuv0",
        typeName: "List<Document<restaurants>>",
      );
  ffai.ProjectStateFieldHandle get searchText =>
      const ffai.ProjectStateFieldHandle(
        name: "searchText",
        key: "pfgmzy7g",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get selectedChipTypes =>
      const ffai.ProjectStateFieldHandle(
        name: "selectedChipTypes",
        key: "w8i4kad4",
        typeName: "List<String>",
      );
  ffai.ProjectStateFieldHandle get selectedType =>
      const ffai.ProjectStateFieldHandle(
        name: "selectedType",
        key: "kyvftymk",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get userLatitude =>
      const ffai.ProjectStateFieldHandle(
        name: "userLatitude",
        key: "a2hobb9b",
        typeName: "Double",
      );
  ffai.ProjectStateFieldHandle get userLongitude =>
      const ffai.ProjectStateFieldHandle(
        name: "userLongitude",
        key: "9ap1p6vn",
        typeName: "Double",
      );
}

abstract final class HomePageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_oa99nxk6",
      type: "Scaffold",
      path: "HomePage",
      name: "HomePage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_0fjy4eyk",
            type: "AppBar",
            path: "HomePage.appBar[0]",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "actions": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "IconButton_dqhkloxe",
                  type: "IconButton",
                  path: "HomePage.appBar[0].actions[0]",
                  name: "MapToggleButton",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
              ],
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_oxbhtr76",
                  type: "Text",
                  path: "HomePage.appBar[0].title[0]",
                  text: "BYOB Finder Philadelphia",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_mavrvd3j",
            type: "Column",
            path: "HomePage.body[0]",
            name: "HomeBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_5gpmz08z",
                type: "Container",
                path: "HomePage.body[0].children[0]",
                name: "ChipsStrip",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Wrap_zmphfp28",
                    type: "Wrap",
                    path: "HomePage.body[0].children[0].children[0]",
                    name: "ChipsWrap",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_lzqpptaq",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[0]",
                        name: "AllChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_w10q7bzx",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[0].children[0]",
                            name: "AllChipSelLabel",
                            text: "All",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_13wzlt77",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[1]",
                        name: "AllChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_hppveg1t",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[1].children[0]",
                            name: "AllChipUnselLabel",
                            text: "All",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_lkzh96b0",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[2]",
                        name: "ItalianChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_yo838nj7",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[2].children[0]",
                            name: "ItalianChipSelLabel",
                            text: "Italian",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_ogfa2489",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[3]",
                        name: "ItalianChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_41phlg6j",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[3].children[0]",
                            name: "ItalianChipUnselLabel",
                            text: "Italian",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_6unblyjx",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[4]",
                        name: "MediterraneanChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_hwhfn8nh",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[4].children[0]",
                            name: "MediterraneanChipSelLabel",
                            text: "Mediterranean",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_plvptwzl",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[5]",
                        name: "MediterraneanChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_jy5p59pn",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[5].children[0]",
                            name: "MediterraneanChipUnselLabel",
                            text: "Mediterranean",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_rol3ngmo",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[6]",
                        name: "JapaneseChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_r42s7q46",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[6].children[0]",
                            name: "JapaneseChipSelLabel",
                            text: "Japanese",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_3u35hjm6",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[7]",
                        name: "JapaneseChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_yi2pxxl4",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[7].children[0]",
                            name: "JapaneseChipUnselLabel",
                            text: "Japanese",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_g604qs6v",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[8]",
                        name: "SeafoodChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_2xuvy00g",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[8].children[0]",
                            name: "SeafoodChipSelLabel",
                            text: "Seafood",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_pflz27y4",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[9]",
                        name: "SeafoodChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_zlnvw4x5",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[9].children[0]",
                            name: "SeafoodChipUnselLabel",
                            text: "Seafood",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_32o03tmg",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[10]",
                        name: "SushiChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_11czptfr",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[10].children[0]",
                            name: "SushiChipSelLabel",
                            text: "Sushi",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_ceb252mp",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[11]",
                        name: "SushiChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_ptkzxvkw",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[11].children[0]",
                            name: "SushiChipUnselLabel",
                            text: "Sushi",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_5l42cy4w",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[12]",
                        name: "PizzaChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_yc11maih",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[12].children[0]",
                            name: "PizzaChipSelLabel",
                            text: "Pizza",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_772nc0gh",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[13]",
                        name: "PizzaChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_r6zo3653",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[13].children[0]",
                            name: "PizzaChipUnselLabel",
                            text: "Pizza",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_0ru7nvzx",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[14]",
                        name: "AsianChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_bxvbmia5",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[14].children[0]",
                            name: "AsianChipSelLabel",
                            text: "Asian",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_wwarppbe",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[15]",
                        name: "AsianChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_869xr51c",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[15].children[0]",
                            name: "AsianChipUnselLabel",
                            text: "Asian",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_5axn1agx",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[16]",
                        name: "MexicanChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_lu6rvb0r",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[16].children[0]",
                            name: "MexicanChipSelLabel",
                            text: "Mexican",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_25nacdtk",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[17]",
                        name: "MexicanChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_i47i2j4n",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[17].children[0]",
                            name: "MexicanChipUnselLabel",
                            text: "Mexican",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_e3xm1g89",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[18]",
                        name: "ThaiChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_s0nvqy6s",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[18].children[0]",
                            name: "ThaiChipSelLabel",
                            text: "Thai",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_dt160blt",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[19]",
                        name: "ThaiChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_qe99qrya",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[19].children[0]",
                            name: "ThaiChipUnselLabel",
                            text: "Thai",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_ihlijd7v",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[20]",
                        name: "RamenChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_ka94y2sg",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[20].children[0]",
                            name: "RamenChipSelLabel",
                            text: "Ramen",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_oslr762m",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[21]",
                        name: "RamenChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_vqxx29xn",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[21].children[0]",
                            name: "RamenChipUnselLabel",
                            text: "Ramen",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_tzphkzbx",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[22]",
                        name: "FrenchChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_bbngibk1",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[22].children[0]",
                            name: "FrenchChipSelLabel",
                            text: "French",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_gmxz6pu6",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[23]",
                        name: "FrenchChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_ysbwem5s",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[23].children[0]",
                            name: "FrenchChipUnselLabel",
                            text: "French",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_exdomi5j",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[24]",
                        name: "OtherChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_5xiipszx",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[24].children[0]",
                            name: "OtherChipSelLabel",
                            text: "Other",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_0nfhegbm",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[25]",
                        name: "OtherChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_9iwc269t",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[25].children[0]",
                            name: "OtherChipUnselLabel",
                            text: "Other",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_eq4nwatj",
                type: "Container",
                path: "HomePage.body[0].children[1]",
                name: "SearchBarContainer",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_ou6tlflv",
                    type: "Row",
                    path: "HomePage.body[0].children[1].children[0]",
                    name: "SearchBarRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "TextField_rlxjxry3",
                        type: "TextField",
                        path: "HomePage.body[0].children[1].children[0].children[0]",
                        name: "SearchField",
                        text: "Search restaurants...",
                        triggers: const <String>[
                          "ON_TEXTFIELD_CHANGE",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "IconButton_p2stslw7",
                        type: "IconButton",
                        path: "HomePage.body[0].children[1].children[0].children[1]",
                        name: "ClearSearchButton",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Stack_81fvlw2w",
                type: "Stack",
                path: "HomePage.body[0].children[2]",
                name: "ViewToggleStack",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ListView_nnz4kk6l",
                    type: "ListView",
                    path: "HomePage.body[0].children[2].children[0]",
                    name: "RestaurantList",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_2iud1s7v",
                        type: "Container",
                        path: "HomePage.body[0].children[2].children[0].children[0]",
                        name: "CardWrapper",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_lxqg6ncf",
                            type: "Container",
                            path: "HomePage.body[0].children[2].children[0].children[0].children[0]",
                            name: "RestaurantCard",
                            componentName: "RestaurantCard",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_9ae7he97",
                    type: "Column",
                    path: "HomePage.body[0].children[2].children[1]",
                    name: "MapViewColumn",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_wl7r2h4m",
                        type: "Container",
                        path: "HomePage.body[0].children[2].children[1].children[0]",
                        name: "MapArea",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "GoogleMap_pj46mjkp",
                            type: "GoogleMap",
                            path: "HomePage.body[0].children[2].children[1].children[0].children[0]",
                            name: "MapArea Inner",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_9slklnrb",
                        type: "Container",
                        path: "HomePage.body[0].children[2].children[1].children[1]",
                        name: "NearestCardsSection",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_cny2ngt7",
                            type: "Column",
                            path: "HomePage.body[0].children[2].children[1].children[1].children[0]",
                            name: "NearestCardsSectionColumn",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_4c6ujflt",
                                type: "Container",
                                path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[0]",
                                name: "NearestTitlePad",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_1u7wg329",
                                    type: "Text",
                                    path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[0].children[0]",
                                    name: "NearestSectionTitle",
                                    text: "BYOBs near you",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "ListView_ymey3asl",
                                type: "ListView",
                                path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1]",
                                name: "NearestCardsList",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_m4wmilee",
                                    type: "Container",
                                    path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0]",
                                    name: "NearestCardWrapper",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_n52k0z6t",
                                        type: "Column",
                                        path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0]",
                                        name: "NearestCardContent",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_b6e3d3ae",
                                            type: "Text",
                                            path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[0]",
                                            name: "NearestCardName",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_sz4m345l",
                                            type: "Text",
                                            path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[1]",
                                            name: "NearestCuisineText",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_u538r7tl",
                                            type: "Container",
                                            path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[2]",
                                            name: "NearestFreeBadge",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_sltr4k1a",
                                                type: "Text",
                                                path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[2].children[0]",
                                                name: "NearestFreeText",
                                                text: "Free BYOB",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_yj5h5ase",
                                            type: "Container",
                                            path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[3]",
                                            name: "NearestCorkageBadge",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_fsixfqps",
                                                type: "Text",
                                                path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[3].children[0]",
                                                name: "NearestCorkageText",
                                                text: "Corkage Fee",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_d346byps",
                                            type: "Container",
                                            path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[4]",
                                            name: "NearestOtherBadge",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_0y56gno1",
                                                type: "Text",
                                                path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[4].children[0]",
                                                name: "NearestOtherText",
                                                text: "Ask Us",
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

