// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final homePageHandle = ffai.ProjectPageHandle<HomePageParams, HomePageState>(
  name: "HomePage",
  key: "Scaffold_oa99nxk6",
  route: "",
  params: const HomePageParams(),
  state: const HomePageState(),
  widgets: HomePageWidgets.tree,
);

final class HomePageParams {
  const HomePageParams();
  ffai.ProjectParamHandle get incomingCuisineFilter =>
      const ffai.ProjectParamHandle(
        name: "incomingCuisineFilter",
        key: "mnvpfukh",
        typeName: "String",
      );
  ffai.ProjectParamHandle get selectedChipFilter =>
      const ffai.ProjectParamHandle(
        name: "selectedChipFilter",
        key: "qk2zyk54",
        typeName: "String",
      );
}

final class HomePageState {
  const HomePageState();
  ffai.ProjectStateFieldHandle get filteredRestaurants =>
      const ffai.ProjectStateFieldHandle(
        name: "filteredRestaurants",
        key: "3g7kiw9o",
        typeName: "List<Document<restaurants>>",
      );
  ffai.ProjectStateFieldHandle get hasLocationPermission =>
      const ffai.ProjectStateFieldHandle(
        name: "hasLocationPermission",
        key: "ik28h6vw",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get isMapView =>
      const ffai.ProjectStateFieldHandle(
        name: "isMapView",
        key: "ydaix0z3",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get nearestThree =>
      const ffai.ProjectStateFieldHandle(
        name: "nearestThree",
        key: "0dj4dvb6",
        typeName: "List<Document<restaurants>>",
      );
  ffai.ProjectStateFieldHandle get restaurants =>
      const ffai.ProjectStateFieldHandle(
        name: "restaurants",
        key: "j1pgjuv0",
        typeName: "List<Document<restaurants>>",
      );
  ffai.ProjectStateFieldHandle get searchText =>
      const ffai.ProjectStateFieldHandle(
        name: "searchText",
        key: "pfgmzy7g",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get selectedChipTypes =>
      const ffai.ProjectStateFieldHandle(
        name: "selectedChipTypes",
        key: "w8i4kad4",
        typeName: "List<String>",
      );
  ffai.ProjectStateFieldHandle get selectedType =>
      const ffai.ProjectStateFieldHandle(
        name: "selectedType",
        key: "kyvftymk",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get userLatitude =>
      const ffai.ProjectStateFieldHandle(
        name: "userLatitude",
        key: "a2hobb9b",
        typeName: "Double",
      );
  ffai.ProjectStateFieldHandle get userLongitude =>
      const ffai.ProjectStateFieldHandle(
        name: "userLongitude",
        key: "9ap1p6vn",
        typeName: "Double",
      );
}

abstract final class HomePageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_oa99nxk6",
      type: "Scaffold",
      path: "HomePage",
      name: "HomePage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_0fjy4eyk",
            type: "AppBar",
            path: "HomePage.appBar[0]",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "actions": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "IconButton_gztod4uz",
                  type: "IconButton",
                  path: "HomePage.appBar[0].actions[0]",
                  name: "MapToggleButton",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
              ],
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_oxbhtr76",
                  type: "Text",
                  path: "HomePage.appBar[0].title[0]",
                  text: "BYOB Map",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_6p49809g",
            type: "Column",
            path: "HomePage.body[0]",
            name: "HomeBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_bpgod3u4",
                type: "Container",
                path: "HomePage.body[0].children[0]",
                name: "ChipsStrip",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Wrap_79wtk1yn",
                    type: "Wrap",
                    path: "HomePage.body[0].children[0].children[0]",
                    name: "ChipsWrap",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_xmwnetmq",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[0]",
                        name: "AllChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_bzc526rr",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[0].children[0]",
                            name: "AllChipSelLabel",
                            text: "All",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_f6yug48d",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[1]",
                        name: "AllChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_tem5zydb",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[1].children[0]",
                            name: "AllChipUnselLabel",
                            text: "All",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_ufllgo8o",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[2]",
                        name: "ItalianChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_h5ikqjvj",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[2].children[0]",
                            name: "ItalianChipSelLabel",
                            text: "Italian",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_df5jeqtu",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[3]",
                        name: "ItalianChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_p2x4se3a",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[3].children[0]",
                            name: "ItalianChipUnselLabel",
                            text: "Italian",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_0le1ky7f",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[4]",
                        name: "MediterraneanChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_jdaspcfo",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[4].children[0]",
                            name: "MediterraneanChipSelLabel",
                            text: "Mediterranean",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_08rdief5",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[5]",
                        name: "MediterraneanChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_ra012j8n",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[5].children[0]",
                            name: "MediterraneanChipUnselLabel",
                            text: "Mediterranean",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_jdpu23vp",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[6]",
                        name: "JapaneseChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_qlmvmb7m",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[6].children[0]",
                            name: "JapaneseChipSelLabel",
                            text: "Japanese",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_3qrwsd1a",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[7]",
                        name: "JapaneseChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_pqo8q34p",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[7].children[0]",
                            name: "JapaneseChipUnselLabel",
                            text: "Japanese",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_cvqav0je",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[8]",
                        name: "SeafoodChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_59jxpa2m",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[8].children[0]",
                            name: "SeafoodChipSelLabel",
                            text: "Seafood",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_vivobhwz",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[9]",
                        name: "SeafoodChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_n8bkt8ks",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[9].children[0]",
                            name: "SeafoodChipUnselLabel",
                            text: "Seafood",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_0fzf5mhm",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[10]",
                        name: "SushiChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_n0aekq19",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[10].children[0]",
                            name: "SushiChipSelLabel",
                            text: "Sushi",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_o99oyyzy",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[11]",
                        name: "SushiChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_dayxpq26",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[11].children[0]",
                            name: "SushiChipUnselLabel",
                            text: "Sushi",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_mv9aarok",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[12]",
                        name: "PizzaChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_qrof6f3w",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[12].children[0]",
                            name: "PizzaChipSelLabel",
                            text: "Pizza",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_ejd0lx7a",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[13]",
                        name: "PizzaChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_xpcdq66j",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[13].children[0]",
                            name: "PizzaChipUnselLabel",
                            text: "Pizza",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_j6npfj0f",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[14]",
                        name: "AsianChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_6ksact15",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[14].children[0]",
                            name: "AsianChipSelLabel",
                            text: "Asian",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_zefb2wpn",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[15]",
                        name: "AsianChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_rrsxmcxh",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[15].children[0]",
                            name: "AsianChipUnselLabel",
                            text: "Asian",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_92w8hpg5",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[16]",
                        name: "MexicanChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_tlhfjj6d",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[16].children[0]",
                            name: "MexicanChipSelLabel",
                            text: "Mexican",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_0roh5dct",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[17]",
                        name: "MexicanChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_uymylsim",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[17].children[0]",
                            name: "MexicanChipUnselLabel",
                            text: "Mexican",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_se9ri8ld",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[18]",
                        name: "ThaiChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_r0qaizlf",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[18].children[0]",
                            name: "ThaiChipSelLabel",
                            text: "Thai",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_g3eltemg",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[19]",
                        name: "ThaiChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_4j22cjg8",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[19].children[0]",
                            name: "ThaiChipUnselLabel",
                            text: "Thai",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_wws04bw2",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[20]",
                        name: "RamenChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_b1l3x4qq",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[20].children[0]",
                            name: "RamenChipSelLabel",
                            text: "Ramen",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_3qcu1inw",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[21]",
                        name: "RamenChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_j949myof",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[21].children[0]",
                            name: "RamenChipUnselLabel",
                            text: "Ramen",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_07axe6g5",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[22]",
                        name: "FrenchChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_415h8rou",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[22].children[0]",
                            name: "FrenchChipSelLabel",
                            text: "French",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_z3gyej3j",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[23]",
                        name: "FrenchChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_hdhfjxvt",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[23].children[0]",
                            name: "FrenchChipUnselLabel",
                            text: "French",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_r43vk78j",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[24]",
                        name: "OtherChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_5qks5rby",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[24].children[0]",
                            name: "OtherChipSelLabel",
                            text: "Other",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_7od028t0",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[25]",
                        name: "OtherChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_m3hwjgpg",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[25].children[0]",
                            name: "OtherChipUnselLabel",
                            text: "Other",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_8xbcl193",
                type: "Container",
                path: "HomePage.body[0].children[1]",
                name: "SearchBarContainer",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_nwl9wl1k",
                    type: "Row",
                    path: "HomePage.body[0].children[1].children[0]",
                    name: "SearchBarRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "TextField_nykxgfwv",
                        type: "TextField",
                        path: "HomePage.body[0].children[1].children[0].children[0]",
                        name: "SearchField",
                        text: "Search restaurants...",
                        triggers: const <String>[
                          "ON_TEXTFIELD_CHANGE",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "IconButton_qe6bir81",
                        type: "IconButton",
                        path: "HomePage.body[0].children[1].children[0].children[1]",
                        name: "ClearSearchButton",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Stack_y004zgfv",
                type: "Stack",
                path: "HomePage.body[0].children[2]",
                name: "ViewToggleStack",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ListView_sls79c2g",
                    type: "ListView",
                    path: "HomePage.body[0].children[2].children[0]",
                    name: "RestaurantList",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_qs2k2hep",
                        type: "Container",
                        path: "HomePage.body[0].children[2].children[0].children[0]",
                        name: "CardWrapper",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_2ywt78x6",
                            type: "Container",
                            path: "HomePage.body[0].children[2].children[0].children[0].children[0]",
                            name: "RestaurantCard",
                            componentName: "RestaurantCard",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_v1rjxgep",
                    type: "Column",
                    path: "HomePage.body[0].children[2].children[1]",
                    name: "MapViewColumn",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_dqs0jy4p",
                        type: "Container",
                        path: "HomePage.body[0].children[2].children[1].children[0]",
                        name: "MapArea",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "GoogleMap_bgg2037m",
                            type: "GoogleMap",
                            path: "HomePage.body[0].children[2].children[1].children[0].children[0]",
                            name: "MapArea Inner",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_24wyz1w3",
                        type: "Container",
                        path: "HomePage.body[0].children[2].children[1].children[1]",
                        name: "NearestCardsSection",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_7eepmvqm",
                            type: "Column",
                            path: "HomePage.body[0].children[2].children[1].children[1].children[0]",
                            name: "NearestCardsSectionColumn",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_gb56dlgj",
                                type: "Container",
                                path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[0]",
                                name: "NearestTitlePad",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_q261xt4b",
                                    type: "Text",
                                    path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[0].children[0]",
                                    name: "NearestSectionTitle",
                                    text: "BYOBs near you",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "ListView_56g4c2pb",
                                type: "ListView",
                                path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1]",
                                name: "NearestCardsList",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_38ben1tw",
                                    type: "Container",
                                    path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0]",
                                    name: "NearestCardWrapper",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_iwxzdt3m",
                                        type: "Column",
                                        path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0]",
                                        name: "NearestCardContent",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_t8e5u4jc",
                                            type: "Text",
                                            path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[0]",
                                            name: "NearestCardName",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_vyps5ji0",
                                            type: "Text",
                                            path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[1]",
                                            name: "NearestCuisineText",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_c630gww0",
                                            type: "Container",
                                            path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[2]",
                                            name: "NearestFreeBadge",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_l64u5dqm",
                                                type: "Text",
                                                path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[2].children[0]",
                                                name: "NearestFreeText",
                                                text: "Free BYOB",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_zmu4dek2",
                                            type: "Container",
                                            path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[3]",
                                            name: "NearestCorkageBadge",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_dxvih3mf",
                                                type: "Text",
                                                path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[3].children[0]",
                                                name: "NearestCorkageText",
                                                text: "Corkage Fee",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_9em7up70",
                                            type: "Container",
                                            path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[4]",
                                            name: "NearestOtherBadge",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_ajn72gtx",
                                                type: "Text",
                                                path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[4].children[0]",
                                                name: "NearestOtherText",
                                                text: "Ask Us",
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

