// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final homePageHandle = ffai.ProjectPageHandle<HomePageParams, HomePageState>(
  name: "HomePage",
  key: "Scaffold_oa99nxk6",
  route: "",
  params: const HomePageParams(),
  state: const HomePageState(),
  widgets: HomePageWidgets.tree,
);

final class HomePageParams {
  const HomePageParams();
  ffai.ProjectParamHandle get incomingCuisineFilter =>
      const ffai.ProjectParamHandle(
        name: "incomingCuisineFilter",
        key: "mnvpfukh",
        typeName: "String",
      );
  ffai.ProjectParamHandle get selectedChipFilter =>
      const ffai.ProjectParamHandle(
        name: "selectedChipFilter",
        key: "qk2zyk54",
        typeName: "String",
      );
}

final class HomePageState {
  const HomePageState();
  ffai.ProjectStateFieldHandle get filteredRestaurants =>
      const ffai.ProjectStateFieldHandle(
        name: "filteredRestaurants",
        key: "3g7kiw9o",
        typeName: "List<Document<restaurants>>",
      );
  ffai.ProjectStateFieldHandle get hasLocationPermission =>
      const ffai.ProjectStateFieldHandle(
        name: "hasLocationPermission",
        key: "ik28h6vw",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get isMapView =>
      const ffai.ProjectStateFieldHandle(
        name: "isMapView",
        key: "ydaix0z3",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get nearestThree =>
      const ffai.ProjectStateFieldHandle(
        name: "nearestThree",
        key: "0dj4dvb6",
        typeName: "List<Document<restaurants>>",
      );
  ffai.ProjectStateFieldHandle get restaurants =>
      const ffai.ProjectStateFieldHandle(
        name: "restaurants",
        key: "j1pgjuv0",
        typeName: "List<Document<restaurants>>",
      );
  ffai.ProjectStateFieldHandle get searchText =>
      const ffai.ProjectStateFieldHandle(
        name: "searchText",
        key: "pfgmzy7g",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get selectedChipTypes =>
      const ffai.ProjectStateFieldHandle(
        name: "selectedChipTypes",
        key: "w8i4kad4",
        typeName: "List<String>",
      );
  ffai.ProjectStateFieldHandle get selectedType =>
      const ffai.ProjectStateFieldHandle(
        name: "selectedType",
        key: "kyvftymk",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get userLatitude =>
      const ffai.ProjectStateFieldHandle(
        name: "userLatitude",
        key: "a2hobb9b",
        typeName: "Double",
      );
  ffai.ProjectStateFieldHandle get userLongitude =>
      const ffai.ProjectStateFieldHandle(
        name: "userLongitude",
        key: "9ap1p6vn",
        typeName: "Double",
      );
}

abstract final class HomePageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_oa99nxk6",
      type: "Scaffold",
      path: "HomePage",
      name: "HomePage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_0fjy4eyk",
            type: "AppBar",
            path: "HomePage.appBar[0]",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "actions": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "IconButton_k5ud1dv5",
                  type: "IconButton",
                  path: "HomePage.appBar[0].actions[0]",
                  name: "MapToggleButton",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
              ],
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_oxbhtr76",
                  type: "Text",
                  path: "HomePage.appBar[0].title[0]",
                  text: "BYOB Finder Philadelphia",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_p0laky74",
            type: "Column",
            path: "HomePage.body[0]",
            name: "HomeBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_avz53vf4",
                type: "Container",
                path: "HomePage.body[0].children[0]",
                name: "ChipsStrip",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Wrap_b0xj0qz0",
                    type: "Wrap",
                    path: "HomePage.body[0].children[0].children[0]",
                    name: "ChipsWrap",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_13w58f49",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[0]",
                        name: "AllChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_wm4bb2ri",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[0].children[0]",
                            name: "AllChipSelLabel",
                            text: "All",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_7vrncgrk",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[1]",
                        name: "AllChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_lzm9d1cv",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[1].children[0]",
                            name: "AllChipUnselLabel",
                            text: "All",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_aa74ao8x",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[2]",
                        name: "ItalianChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_fcptuihr",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[2].children[0]",
                            name: "ItalianChipSelLabel",
                            text: "Italian",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_8qn602ws",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[3]",
                        name: "ItalianChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_qanqldu5",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[3].children[0]",
                            name: "ItalianChipUnselLabel",
                            text: "Italian",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_ma0r6oi8",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[4]",
                        name: "MediterraneanChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_ly0kglnj",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[4].children[0]",
                            name: "MediterraneanChipSelLabel",
                            text: "Mediterranean",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_mbm0p7k9",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[5]",
                        name: "MediterraneanChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_9k1n7shj",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[5].children[0]",
                            name: "MediterraneanChipUnselLabel",
                            text: "Mediterranean",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_5qh2qu5k",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[6]",
                        name: "JapaneseChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_qshp9iux",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[6].children[0]",
                            name: "JapaneseChipSelLabel",
                            text: "Japanese",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_vo3btg03",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[7]",
                        name: "JapaneseChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_vat89uux",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[7].children[0]",
                            name: "JapaneseChipUnselLabel",
                            text: "Japanese",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_rpy4w5oq",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[8]",
                        name: "SeafoodChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_2012pp2m",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[8].children[0]",
                            name: "SeafoodChipSelLabel",
                            text: "Seafood",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_ru1ukz6k",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[9]",
                        name: "SeafoodChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_apwe8blk",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[9].children[0]",
                            name: "SeafoodChipUnselLabel",
                            text: "Seafood",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_xhoxed70",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[10]",
                        name: "SushiChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_hqzs51wg",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[10].children[0]",
                            name: "SushiChipSelLabel",
                            text: "Sushi",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_01skfwea",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[11]",
                        name: "SushiChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_7gz02loa",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[11].children[0]",
                            name: "SushiChipUnselLabel",
                            text: "Sushi",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_lsfg9juz",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[12]",
                        name: "PizzaChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_4p234wch",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[12].children[0]",
                            name: "PizzaChipSelLabel",
                            text: "Pizza",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_vo4l0fpt",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[13]",
                        name: "PizzaChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_5woj63p9",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[13].children[0]",
                            name: "PizzaChipUnselLabel",
                            text: "Pizza",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_j3v4i6ru",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[14]",
                        name: "AsianChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_7jogx6hs",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[14].children[0]",
                            name: "AsianChipSelLabel",
                            text: "Asian",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_h32q2lhe",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[15]",
                        name: "AsianChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_fksr9plr",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[15].children[0]",
                            name: "AsianChipUnselLabel",
                            text: "Asian",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_w6hpyo36",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[16]",
                        name: "MexicanChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_ohgkxoio",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[16].children[0]",
                            name: "MexicanChipSelLabel",
                            text: "Mexican",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_uvfq4fhy",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[17]",
                        name: "MexicanChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_721vyho5",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[17].children[0]",
                            name: "MexicanChipUnselLabel",
                            text: "Mexican",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_v6c2vzvz",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[18]",
                        name: "ThaiChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_mlusj8f7",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[18].children[0]",
                            name: "ThaiChipSelLabel",
                            text: "Thai",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_hxkdxppe",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[19]",
                        name: "ThaiChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_1src3tpp",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[19].children[0]",
                            name: "ThaiChipUnselLabel",
                            text: "Thai",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_8envmru0",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[20]",
                        name: "RamenChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_ivownqo9",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[20].children[0]",
                            name: "RamenChipSelLabel",
                            text: "Ramen",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_x62mbe0v",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[21]",
                        name: "RamenChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_awu4j95y",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[21].children[0]",
                            name: "RamenChipUnselLabel",
                            text: "Ramen",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_bapj781i",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[22]",
                        name: "FrenchChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_00272tpq",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[22].children[0]",
                            name: "FrenchChipSelLabel",
                            text: "French",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_4uzs0peh",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[23]",
                        name: "FrenchChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_czbho3gt",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[23].children[0]",
                            name: "FrenchChipUnselLabel",
                            text: "French",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_yszumyoi",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[24]",
                        name: "OtherChipSel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_kgex678j",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[24].children[0]",
                            name: "OtherChipSelLabel",
                            text: "Other",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_7kojcamz",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[0].children[25]",
                        name: "OtherChipUnsel",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_alwmovau",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[0].children[25].children[0]",
                            name: "OtherChipUnselLabel",
                            text: "Other",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_jtmodkvw",
                type: "Container",
                path: "HomePage.body[0].children[1]",
                name: "SearchBarContainer",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_u6oyp4aw",
                    type: "Row",
                    path: "HomePage.body[0].children[1].children[0]",
                    name: "SearchBarRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "TextField_r5l1qr4b",
                        type: "TextField",
                        path: "HomePage.body[0].children[1].children[0].children[0]",
                        name: "SearchField",
                        text: "Search restaurants...",
                        triggers: const <String>[
                          "ON_TEXTFIELD_CHANGE",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "IconButton_70a9e5wy",
                        type: "IconButton",
                        path: "HomePage.body[0].children[1].children[0].children[1]",
                        name: "ClearSearchButton",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Stack_cc3c95th",
                type: "Stack",
                path: "HomePage.body[0].children[2]",
                name: "ViewToggleStack",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ListView_08vc01d8",
                    type: "ListView",
                    path: "HomePage.body[0].children[2].children[0]",
                    name: "RestaurantList",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_0fb24woi",
                        type: "Container",
                        path: "HomePage.body[0].children[2].children[0].children[0]",
                        name: "CardWrapper",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_wwvcb9mn",
                            type: "Container",
                            path: "HomePage.body[0].children[2].children[0].children[0].children[0]",
                            name: "RestaurantCard",
                            componentName: "RestaurantCard",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_tyumpfdx",
                    type: "Column",
                    path: "HomePage.body[0].children[2].children[1]",
                    name: "MapViewColumn",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_y7q5oy2z",
                        type: "Container",
                        path: "HomePage.body[0].children[2].children[1].children[0]",
                        name: "MapArea",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "GoogleMap_69tx6597",
                            type: "GoogleMap",
                            path: "HomePage.body[0].children[2].children[1].children[0].children[0]",
                            name: "MapArea Inner",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_hv2vhwaj",
                        type: "Container",
                        path: "HomePage.body[0].children[2].children[1].children[1]",
                        name: "NearestCardsSection",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_swgyyvk0",
                            type: "Column",
                            path: "HomePage.body[0].children[2].children[1].children[1].children[0]",
                            name: "NearestCardsSectionColumn",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_0k5yx0ej",
                                type: "Container",
                                path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[0]",
                                name: "NearestTitlePad",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_mypy9jg4",
                                    type: "Text",
                                    path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[0].children[0]",
                                    name: "NearestSectionTitle",
                                    text: "BYOBs near you",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "ListView_9oiedlsd",
                                type: "ListView",
                                path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1]",
                                name: "NearestCardsList",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_0oz0dxmc",
                                    type: "Container",
                                    path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0]",
                                    name: "NearestCardWrapper",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_p8ub6fdg",
                                        type: "Column",
                                        path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0]",
                                        name: "NearestCardContent",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_c1du6p70",
                                            type: "Text",
                                            path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[0]",
                                            name: "NearestCardName",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_t7scxes4",
                                            type: "Text",
                                            path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[1]",
                                            name: "NearestCuisineText",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_pqbkwabj",
                                            type: "Container",
                                            path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[2]",
                                            name: "NearestFreeBadge",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_uoernto8",
                                                type: "Text",
                                                path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[2].children[0]",
                                                name: "NearestFreeText",
                                                text: "Free BYOB",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_o4j49bf6",
                                            type: "Container",
                                            path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[3]",
                                            name: "NearestCorkageBadge",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_0cvh4adt",
                                                type: "Text",
                                                path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[3].children[0]",
                                                name: "NearestCorkageText",
                                                text: "Corkage Fee",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_grlgu5gc",
                                            type: "Container",
                                            path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[4]",
                                            name: "NearestOtherBadge",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_9p3kp10l",
                                                type: "Text",
                                                path: "HomePage.body[0].children[2].children[1].children[1].children[0].children[1].children[0].children[0].children[4].children[0]",
                                                name: "NearestOtherText",
                                                text: "Ask Us",
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

