// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final restaurantDetailPageHandle = ffai.ProjectPageHandle<RestaurantDetailPageParams, RestaurantDetailPageState>(
  name: "RestaurantDetailPage",
  key: "Scaffold_p08wvbbc",
  route: "restaurant-detail",
  params: const RestaurantDetailPageParams(),
  state: const RestaurantDetailPageState(),
  widgets: RestaurantDetailPageWidgets.tree,
);

final class RestaurantDetailPageParams {
  const RestaurantDetailPageParams();
  ffai.ProjectParamHandle get address =>
      const ffai.ProjectParamHandle(
        name: "address",
        key: "5f1h9n2b",
        typeName: "String",
      );
  ffai.ProjectParamHandle get corkageFeeType =>
      const ffai.ProjectParamHandle(
        name: "corkageFeeType",
        key: "vcy3im1j",
        typeName: "String",
      );
  ffai.ProjectParamHandle get coverImageUrl =>
      const ffai.ProjectParamHandle(
        name: "coverImageUrl",
        key: "h0jjdoso",
        typeName: "String",
      );
  ffai.ProjectParamHandle get cuisineType =>
      const ffai.ProjectParamHandle(
        name: "cuisineType",
        key: "ygt3tdj1",
        typeName: "String",
      );
  ffai.ProjectParamHandle get cuisineTypeNote =>
      const ffai.ProjectParamHandle(
        name: "cuisineTypeNote",
        key: "j1q6a2ll",
        typeName: "String",
      );
  ffai.ProjectParamHandle get latitude =>
      const ffai.ProjectParamHandle(
        name: "latitude",
        key: "9id2985w",
        typeName: "Double",
      );
  ffai.ProjectParamHandle get longitude =>
      const ffai.ProjectParamHandle(
        name: "longitude",
        key: "0a5qd02n",
        typeName: "Double",
      );
  ffai.ProjectParamHandle get phone =>
      const ffai.ProjectParamHandle(
        name: "phone",
        key: "xae9y6ux",
        typeName: "String",
      );
  ffai.ProjectParamHandle get restaurantName =>
      const ffai.ProjectParamHandle(
        name: "restaurantName",
        key: "jxkhoyu7",
        typeName: "String",
      );
}

final class RestaurantDetailPageState {
  const RestaurantDetailPageState();
}

abstract final class RestaurantDetailPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_p08wvbbc",
      type: "Scaffold",
      path: "RestaurantDetailPage",
      name: "RestaurantDetailPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_3ghjp9k5",
            type: "AppBar",
            path: "RestaurantDetailPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_cwguk6gw",
                  type: "Text",
                  path: "RestaurantDetailPage.appBar[0].title[0]",
                  name: "AppBar Title",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_y1uignhn",
            type: "Column",
            path: "RestaurantDetailPage.body[0]",
            name: "DetailBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Image_4c684yw6",
                type: "Image",
                path: "RestaurantDetailPage.body[0].children[0]",
                name: "CoverImage",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_go35k65j",
                type: "Container",
                path: "RestaurantDetailPage.body[0].children[1]",
                name: "InfoSection",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_hr25eta5",
                    type: "Column",
                    path: "RestaurantDetailPage.body[0].children[1].children[0]",
                    name: "InfoColumn",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_nssqq84h",
                        type: "Text",
                        path: "RestaurantDetailPage.body[0].children[1].children[0].children[0]",
                        name: "NameText",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_vdvk3axy",
                        type: "Text",
                        path: "RestaurantDetailPage.body[0].children[1].children[0].children[1]",
                        name: "CuisineText",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_aaz5pk6s",
                        type: "Row",
                        path: "RestaurantDetailPage.body[0].children[1].children[0].children[2]",
                        name: "BadgeRow",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_bycuvm9z",
                            type: "Container",
                            path: "RestaurantDetailPage.body[0].children[1].children[0].children[2].children[0]",
                            name: "FreeBadge",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_ch9gndsy",
                                type: "Text",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[2].children[0].children[0]",
                                name: "FreeBadgeText",
                                text: "Free BYOB",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_lv49alb5",
                            type: "Container",
                            path: "RestaurantDetailPage.body[0].children[1].children[0].children[2].children[1]",
                            name: "CorkageFeeBadge",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_qi9l9pxf",
                                type: "Text",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[2].children[1].children[0]",
                                name: "CorkageFeeText",
                                text: "Corkage Fee",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_cj73xvlz",
                            type: "Container",
                            path: "RestaurantDetailPage.body[0].children[1].children[0].children[2].children[2]",
                            name: "AskUsBadge",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_c6qvfmvq",
                                type: "Text",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[2].children[2].children[0]",
                                name: "AskUsText",
                                text: "Ask Us",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_znllo6gh",
                        type: "Container",
                        path: "RestaurantDetailPage.body[0].children[1].children[0].children[3]",
                        name: "Spacer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_z1crqelh",
                        type: "Container",
                        path: "RestaurantDetailPage.body[0].children[1].children[0].children[4]",
                        name: "AddressContainer",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_gs7pdwjg",
                            type: "Row",
                            path: "RestaurantDetailPage.body[0].children[1].children[0].children[4].children[0]",
                            name: "AddressRow",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_josy5bot",
                                type: "Icon",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[4].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_euvjg0oa",
                                type: "Container",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[4].children[0].children[1]",
                                name: "Spacer",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_sdbb1hqg",
                                type: "Text",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[4].children[0].children[2]",
                                name: "AddressText",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_bts3h3ze",
                        type: "Container",
                        path: "RestaurantDetailPage.body[0].children[1].children[0].children[5]",
                        name: "PhoneContainer",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_d80fxxbw",
                            type: "Row",
                            path: "RestaurantDetailPage.body[0].children[1].children[0].children[5].children[0]",
                            name: "PhoneRow",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_zmc8up9d",
                                type: "Icon",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[5].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_fks9jzey",
                                type: "Container",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[5].children[0].children[1]",
                                name: "Spacer",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_gvnkt5ay",
                                type: "Text",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[5].children[0].children[2]",
                                name: "PhoneText",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_3rkqozz5",
                        type: "Container",
                        path: "RestaurantDetailPage.body[0].children[1].children[0].children[6]",
                        name: "Spacer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_96ew40w5",
                        type: "Button",
                        path: "RestaurantDetailPage.body[0].children[1].children[0].children[7]",
                        name: "GetDirectionsButton",
                        text: "Get Directions",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

