// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final restaurantDetailPageHandle = ffai.ProjectPageHandle<RestaurantDetailPageParams, RestaurantDetailPageState>(
  name: "RestaurantDetailPage",
  key: "Scaffold_p08wvbbc",
  route: "restaurant-detail",
  params: const RestaurantDetailPageParams(),
  state: const RestaurantDetailPageState(),
  widgets: RestaurantDetailPageWidgets.tree,
);

final class RestaurantDetailPageParams {
  const RestaurantDetailPageParams();
  ffai.ProjectParamHandle get address =>
      const ffai.ProjectParamHandle(
        name: "address",
        key: "5f1h9n2b",
        typeName: "String",
      );
  ffai.ProjectParamHandle get corkageFeeType =>
      const ffai.ProjectParamHandle(
        name: "corkageFeeType",
        key: "vcy3im1j",
        typeName: "String",
      );
  ffai.ProjectParamHandle get coverImageUrl =>
      const ffai.ProjectParamHandle(
        name: "coverImageUrl",
        key: "h0jjdoso",
        typeName: "String",
      );
  ffai.ProjectParamHandle get cuisineType =>
      const ffai.ProjectParamHandle(
        name: "cuisineType",
        key: "ygt3tdj1",
        typeName: "String",
      );
  ffai.ProjectParamHandle get cuisineTypeNote =>
      const ffai.ProjectParamHandle(
        name: "cuisineTypeNote",
        key: "j1q6a2ll",
        typeName: "String",
      );
  ffai.ProjectParamHandle get latitude =>
      const ffai.ProjectParamHandle(
        name: "latitude",
        key: "9id2985w",
        typeName: "Double",
      );
  ffai.ProjectParamHandle get longitude =>
      const ffai.ProjectParamHandle(
        name: "longitude",
        key: "0a5qd02n",
        typeName: "Double",
      );
  ffai.ProjectParamHandle get phone =>
      const ffai.ProjectParamHandle(
        name: "phone",
        key: "xae9y6ux",
        typeName: "String",
      );
  ffai.ProjectParamHandle get restaurantName =>
      const ffai.ProjectParamHandle(
        name: "restaurantName",
        key: "jxkhoyu7",
        typeName: "String",
      );
}

final class RestaurantDetailPageState {
  const RestaurantDetailPageState();
}

abstract final class RestaurantDetailPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_p08wvbbc",
      type: "Scaffold",
      path: "RestaurantDetailPage",
      name: "RestaurantDetailPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_rvuhtu2w",
            type: "AppBar",
            path: "RestaurantDetailPage.appBar[0]",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "leading": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "IconButton_39amxoc3",
                  type: "IconButton",
                  path: "RestaurantDetailPage.appBar[0].leading[0]",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
              ],
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_4p5o03bv",
                  type: "Text",
                  path: "RestaurantDetailPage.appBar[0].title[0]",
                  name: "AppBar Title",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_7b3pz5cp",
            type: "Column",
            path: "RestaurantDetailPage.body[0]",
            name: "DetailBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Image_rgq4nkmg",
                type: "Image",
                path: "RestaurantDetailPage.body[0].children[0]",
                name: "CoverImage",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_pu5vkpoh",
                type: "Container",
                path: "RestaurantDetailPage.body[0].children[1]",
                name: "InfoSection",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_gvdb8r1q",
                    type: "Column",
                    path: "RestaurantDetailPage.body[0].children[1].children[0]",
                    name: "InfoColumn",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_kzlqfb7x",
                        type: "Text",
                        path: "RestaurantDetailPage.body[0].children[1].children[0].children[0]",
                        name: "NameText",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_931c28li",
                        type: "Container",
                        path: "RestaurantDetailPage.body[0].children[1].children[0].children[1]",
                        name: "CuisineTagsContainer",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "ListView_zs1bjhid",
                            type: "ListView",
                            path: "RestaurantDetailPage.body[0].children[1].children[0].children[1].children[0]",
                            name: "CuisineTagsList",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_bszrvbm9",
                                type: "Container",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[1].children[0].children[0]",
                                name: "CuisineTag",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_j7y2ewel",
                                    type: "Text",
                                    path: "RestaurantDetailPage.body[0].children[1].children[0].children[1].children[0].children[0].children[0]",
                                    name: "CuisineTagText",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_d128yyns",
                        type: "Row",
                        path: "RestaurantDetailPage.body[0].children[1].children[0].children[2]",
                        name: "BadgeRow",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_k1ui61rn",
                            type: "Container",
                            path: "RestaurantDetailPage.body[0].children[1].children[0].children[2].children[0]",
                            name: "FreeBadge",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_9i4u772x",
                                type: "Text",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[2].children[0].children[0]",
                                name: "FreeBadgeText",
                                text: "Free BYOB",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_du9adp0r",
                            type: "Container",
                            path: "RestaurantDetailPage.body[0].children[1].children[0].children[2].children[1]",
                            name: "CorkageFeeBadge",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_onagl7ba",
                                type: "Text",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[2].children[1].children[0]",
                                name: "CorkageFeeText",
                                text: "Corkage Fee",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_qld28xqf",
                            type: "Container",
                            path: "RestaurantDetailPage.body[0].children[1].children[0].children[2].children[2]",
                            name: "AskUsBadge",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_kolembpo",
                                type: "Text",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[2].children[2].children[0]",
                                name: "AskUsText",
                                text: "Ask Us",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_6whvxnou",
                        type: "Container",
                        path: "RestaurantDetailPage.body[0].children[1].children[0].children[3]",
                        name: "Spacer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_k9jonxd8",
                        type: "Container",
                        path: "RestaurantDetailPage.body[0].children[1].children[0].children[4]",
                        name: "AddressContainer",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_y34vf2zz",
                            type: "Row",
                            path: "RestaurantDetailPage.body[0].children[1].children[0].children[4].children[0]",
                            name: "AddressRow",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_vxfoyand",
                                type: "Icon",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[4].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_4d7n0mir",
                                type: "Container",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[4].children[0].children[1]",
                                name: "Spacer",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_fj30z0jn",
                                type: "Text",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[4].children[0].children[2]",
                                name: "AddressText",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_k2n07qjn",
                        type: "Container",
                        path: "RestaurantDetailPage.body[0].children[1].children[0].children[5]",
                        name: "PhoneContainer",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_umf7ix4a",
                            type: "Row",
                            path: "RestaurantDetailPage.body[0].children[1].children[0].children[5].children[0]",
                            name: "PhoneRow",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_62s40ktm",
                                type: "Icon",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[5].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_bbmwikpr",
                                type: "Container",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[5].children[0].children[1]",
                                name: "Spacer",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_zh8w52m1",
                                type: "Text",
                                path: "RestaurantDetailPage.body[0].children[1].children[0].children[5].children[0].children[2]",
                                name: "PhoneText",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_yjjv2vlh",
                        type: "Container",
                        path: "RestaurantDetailPage.body[0].children[1].children[0].children[6]",
                        name: "Spacer",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_zea7lcgl",
                        type: "Button",
                        path: "RestaurantDetailPage.body[0].children[1].children[0].children[7]",
                        name: "GetDirectionsButton",
                        text: "Get Directions",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

